### ISSUE TITLE
Minor timing bug when checking investments

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#10]
(This is a minor issue unlikely to affect many users or many investments.)

There's a small logical error in the way check_investments timing and upvote counts. Basically, if a bunch of people make investments around the same time, then 6 hours later, only the _first_ investment of that bunch will have his investment evaluated at 6 hours---the rest will have their investments evaluated at 6hrs+1sec, 6hrs+2sec, 6hrs+3sec, etc.

So if sixty people camping /new all invest in a new meme simultaneously, the one who invested last by a few milliseconds would unfairly get the benefit of an extra minute's worth of upvotes six hours later. (Like I said, this is not a big deal unless you see lots of bursts of investing activity or you increase your 1s loop delay.)

**Comment by thecsw** [comment]
I just deleted the 1 second timer. We will see how it goes. Thanks for the issue!
