### ISSUE TITLE
Make it easy to quickly capture a backup of the live database

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#100]
We should be in the habit of backing up the live database every time we make a major change to the bot. We should make that as easy as possible (maybe just a script that can be run from the server, or maybe a service that automatically captures periodic backups).

**Comment by rickles42** [comment]
mysqldump may be all we need for this...

**Comment by thecsw** [comment]
Maybe we can set up adminer that can export everything in `.sql`?

**Comment by thecsw** [comment]
Okay, I think we know what to do, closing this for now.

**Comment by rickles42** [comment]
@thecsw For future reference the typical behavior is to leave an issue open until the PR that fixes it has been merged into the main branch. If you're worried about someone else seeing the issue and accidentally wasting effort fixing something you're already working on, then you can just leave a comment in the issue conversation calling dibs 😄
