### ISSUE TITLE
Make chart dates more universal

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#105]
Easy tweak:

Currently, the dates on the website's investment chart go like: `8/6`, `9/6`, `10/6`. As a [silly American](https://en.wikipedia.org/wiki/Date_format_by_country) this confuses me because I expect dates like `6/8`, `6/9`, `6/10`.

Requesting that we localize the chart dates, or at least update them to something slightly more intuitive for those visitors like me: something like `8 June`, `9 June`, `10 June` would be fine.

**Comment by DaliTimelord** [comment]
Year Month Day for the ultimate disambiguation?

**Comment by rickles42** [comment]
https://xkcd.com/1179/ 😄

**Comment by robalb** [comment]
As a silly european i really liked dd-mm, but ok, i guess something like `6 jun` `23 sept` can be more intuitive
