### ISSUE TITLE
Unused invest_again_org in messages.py

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#124]
Looks like @thecsw added the `invest_again_org` string to `messages.py` at one point as part of a feature to prevent users from having more than one active investment in a given meme. But since then, the feature to enforce it has been removed. If intentional, we should also remove the message. If accidental, we should put the enforcement logic back.

**Comment by thecsw** [comment]
Hmm, yeah. I just want to know, should we keep the feature or should I just remove it completely? The formula is going to be a bit more difficult and users should not be able to abuse it.

**Comment by rickles42** [comment]
I think we should just remove the feature. Like you say it doesn't seem like a major target for abuse.

**Comment by thecsw** [comment]
Okay, I will make a pull request.
