### ISSUE TITLE
Bot drops a command when there is too much inactive time between commands

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#141]
Whenever `bot` goes too long without querying the database, we see an error log message like this:

```
2018-06-30  9:01:13 139758305470208 [Warning] Aborted connection 8 to db: 'mysql' user: 'mysql' host: '172.18.0.6' (Got timeout reading communication packets)
```

I think this has to do with how SQLAlchemy manages its pool of connections to the database. If those connections aren't used, they time out. This means the next time `bot` _does_ try to use the db, the operation fails. Usually that means the bot never reacts to the dropped command.

**Comment by rickles42** [comment]
The cause seems to have been that the Docker container for MariaDB sets a very low `wait_timeout` value of ten minutes (see [this issue](https://github.com/docker-library/mariadb/issues/113) from their GitHub), which means that the connections SQLAlchemy spins up will expire if they aren't used every 10 minutes. I fixed this by telling SQLAlchemy to recycle its connections every 1 minute, which keeps them fresh and not expired.

**Comment by thecsw** [comment]
Awesome!
