### ISSUE TITLE
Cosmetic reward for Beta Billionaires

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#146]
We need to finish planning this and implement it so they can bask in their prestige!

**Comment by robalb** [comment]
right, i'll start working on it

**Comment by rickles42** [comment]
Which approach(es) should we take? I remember the following proposals:

1. Put something on their memes.market profile and/or next to their name in the memes.market leaderboard.

2. Make a dedicated Hall of Fame on memes.market and add them to it.

3. Add some inline content to the bot's Reddit responses to them (like an emoji or something, sort of like flair).

**Comment by robalb** [comment]
if we are planning to do other market resets in future, we could make a wall of fame page with the best traders of all the past seasons. Otherwise something on their names on memes.market (maybe also in the bot responses) would be very easy to implement

**Comment by rickles42** [comment]
I like the hall of fame idea, and I think there's a reasonable chance we'll want to reset the scores again in the future.

**Comment by jovialis** [comment]
I say we give them a super fancy flair and give them a hall of fame page on the website. Give them each the option to write a silly/goofy blurb about themselves and why they're on the hall of fame, and maybe something else.

**Comment by jimbobur** [comment]
@rickles42 I like all three of those ideas!

**Comment by rickles42** [comment]
Okay it sounds like most folks are in favor of a Hall of Fame at least, so I think @robalb should go ahead and start on that. We can add more rewards later if we feel like it's necessary.

**Comment by thecsw** [comment]
Okay, we have the beta leaderboards now. Closing this issue. Please refer to #172 if you have questions.
