### ISSUE TITLE
!Help message is triggered by the bot's own comments

### ISSUE THREAD

**Issue by Wattsy2020** [thecsw/memeinvestor_bot#15]
Bot messages include the line "For more information type !help", which triggers the bot itself. Comment thread for reference: https://www.reddit.com/r/MemeEconomy/comments/8lmryv/versatile_and_easy_to_use_format/dzh4zun/

**Comment by thecsw** [comment]
It is not my bot and my bot never responded to itself!

I don't know what the second author changed in the code, my bot never did that.
Check the comment I left here #16 and here #17
