### ISSUE TITLE
User can declare broke when they shouldn't be able to

### ISSUE THREAD

**Issue by jovialis** [thecsw/memeinvestor_bot#150]
The bot recognizes that a user has 0 balance and declares them broke, even if they currently have active investments.

This could likely be resolved by ensuring the user has 0 open transactions before granting them their bankruptcy loan.

Hi Slackbot!

**Comment by rickles42** [comment]
@cdh-dev I know I said I agreed with you earlier that this was a problem, but now that I look at the code I think we already check for open transactions like you suggest:

``` python
        active = sess.query(func.count(Investment.id)).\
            filter(Investment.done == 0).\
            filter(Investment.name == investor.name).\
            scalar()

        if active > 0:
            return comment.reply_wrap(message.modify_broke_active(active))
```

You should double check me though. That's in the `broke()` method in `main.py`.

**Comment by rickles42** [comment]
@cdh-dev I'm closing this issue, but feel free to double check my claim above and I'll re-open if I've missed something.
