### ISSUE TITLE
Bot should handle locked comment threads gracefully

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#155]
In the current design, if someone has used `!invest` on a post that later gets locked, then the bot gets stuck when it comes back in 4 hours and tries to update their investment (it can't because the comments are locked).

The bot should not get stuck on these cases. It should either process their matured investment and just not reply, or it should drop the investment altogether (perhaps refund the original invested amount). Either way it should move on.

**Comment by robalb** [comment]
This behaviour should be also applied to deleted threads

**Comment by rickles42** [comment]
I asked the mods about this and the bot ought to be able to comment within locked threads, as well as edit its own comments within locked threads. I think the failure we saw the other day was not due to the thread being locked, so this issue is not an actual problem. Closing.
