### ISSUE TITLE
Bot incorrectly calculated profit/loss, or am I being dumb?

### ISSUE THREAD

**Issue by simon--poole** [thecsw/memeinvestor_bot#156]
For example:

* 250 invested @ 2 upvotes. 6 hours later - 35 upvotes. [Loses 125](https://www.reddit.com/r/MemeEconomy/comments/8vanyq/simple_yet_effective_new_format_invest_now/e1lugii/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage)
* 250 @ 2, 6 hours later - 7. [Loses 185](https://www.reddit.com/r/MemeEconomy/comments/8vanyq/simple_yet_effective_new_format_invest_now/e1lugii/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage)
* 250 invested @ 18, 6 hours later - 101. [Loses 31](https://www.reddit.com/r/MemeEconomy/comments/8vahp3/hot_meme_template_in_comments/e1lucug/?context=3&utm_content=context&utm_medium=message&utm_source=reddit&utm_name=frontpage)

I'm aware of the 2 hours delay on the upvotes check but surely a topic wouldn't go 2 -> 1 within 4 hours, then bounce back that much in the last 2?

**Comment by rickles42** [comment]
Hey @simon--poole, thanks for reaching out. You're definitely not being dumb, but it does look like the bot is behaving correctly. You're just running into the new "high risk/high reward" behavior.

To be more specific:

 - If you invest at 2 upvotes, the meme needs to hit 45 total upvotes in four hours for you to break even.

 - If you invest at 18 upvotes, the meme needs to hit 65 total upvotes in four hours for you to break even. This one only hit about 60 after four hours, so you didn't quite break even. Then it got the other ~40 upvotes over the next two hours.

Making money on small memes is pretty tough! You have to really pick 'em well, even just to break even. But we're always looking at the formula and how it can be tuned.

I'm closing this issue but feel free to reply @me if you have any other questions about it.
