### ISSUE TITLE
Irrational logic with memes becoming normified

### ISSUE THREAD

**Issue by eleeve** [thecsw/memeinvestor_bot#163]
When a meme becomes normified and a post explaining it is posted to meme economy, you can still invest in it and if the post gets many upvotes the bot will think it is a successful investment, but in reality it is not. This feels irrational.

**Comment by rickles42** [comment]
Hi @eleeve, thanks for the feedback. Can you post a screenshot or link to a couple examples of what you're talking about? There may not be any way for the bot to distinguish actual meme templates (which people should be able to invest in) from discussion posts (which people should not be able to invest in). But an example or two could let us take a look.

**Comment by eleeve** [comment]
This post https://www.reddit.com/r/MemeEconomy/comments/8v5ama/thought_id_sell_this_nice_normy_meme_any_buyers/?utm_source=reddit-android , for example has sell in it's title and sell tag. Searching specific string or looking at the tag of the post could help decide whether post could be investible or not.

**Comment by robalb** [comment]
recognizing keywords in the title is kinda complicated, but we could ask the mods to add a tag like 'no investments' that tells the bot to ignore posts having it. this could also be useful for announcements and various non-meme posts

**Comment by rickles42** [comment]
I like the suggestion from @robalb, except I wouldn't want the bot to create additional work for the mods (not sure if they already take time to categorize every post). But I believe it would be simple to implement in the bot.

**Comment by thecsw** [comment]
Yeah. What we can do is a simple regex. If OP has `(no invest)` keyword, the bot can just ignore the post.

**Comment by jimbobur** [comment]
Is it possible to read the post flair using the Reddit API?

**Comment by rickles42** [comment]
Yes.

**Comment by rickles42** [comment]
I haven't noticed major problems with this so I'm going to go ahead and close this issue. We can revisit this in the future and work with the mods to explicitly tag meta posts if it becomes a problem.
