### ISSUE TITLE
Bot is causing infinite calls to self.

### ISSUE THREAD

**Issue by sorahavok** [thecsw/memeinvestor_bot#18]
Whenever a user attempts to !help or !create the bot will print the help text which contains !help which will cause the !help text to be printed again which causes the same issue [example](https://www.reddit.com/r/MemeEconomy/comments/8lmryv/versatile_and_easy_to_use_format/dzh60y8).

One easy way to fix this would be to add a !ignore command to [main.py](https://github.com/thecsw/memeinvestor_bot/blob/master/src/main.py) and check for it first before any of the other commands around this line in [main.py](https://github.com/thecsw/memeinvestor_bot/blob/master/src/main.py#L201). Then have the !ignore as one of the listed commands in the !help [message.py](https://github.com/thecsw/memeinvestor_bot/blob/master/src/message.py) which would both solve the problem and give a way for users to demonstrate the commands someone would need without triggering them.

**Comment by thecsw** [comment]
This is not an issue of my bot, the bot right now is buggy and I think that the owner of the second bot deleted some code that caused the bot to spiral in infinite recalls. Refer to #15 for details or take a look at the original main.py again.
