### ISSUE TITLE
Reconstruct !invest response body instead of retrieving it

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#181]
We can save an API call in `calculator.py` if we avoid calling `response.body` to get our response text for editing. Instead we can just reconstruct our original response text offline, since we have all the information we used to build the original response text.

**Comment by rickles42** [comment]
Just realized it won't be possible to exactly reconstruct the original message, since the user's balance could have changed since they made the investment.

But the more I look at the `!invest` response, the more I think it could be rephrased and cleaned up a bit:

- It's slightly confusing to see [stuff like](https://www.reddit.com/r/memeinvestor_test/comments/8yrl88/testerino/e2d8qmq) "Your new balance is 713... UPDATE: You lost 81 coins... Your current balance is 757"

- Also might be kind of awkward to see stuff like "125 MemeCoins successfully invested! … It was unsuccessful!"

So I think I'll try to kill two birds with one stone and rewrite the response entirely, in such a way that the edited response can be done without retrieving the original text, and in a way that's a bit clearer.

**Comment by thecsw** [comment]
You mean `message.py`?

**Comment by rickles42** [comment]
Yes, this fix is mostly/entirely in `message.py` and `calculate.py`.
