### ISSUE TITLE
Backfill new Investments column final_upvotes with data from older investments

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#193]
The new `final_upvotes` column has null values for investments that matured before it was added. We should backfill it with data so people can have more complete investment histories.

**Comment by robalb** [comment]
We could get the data from other investments that happened around the same time of the investment evaluation. Something like (pseudocode) `Select upvotes from investments where postID = (same postId as the one we want to fill) and time = (initialTime + 4h ±margin)`

**Comment by rickles42** [comment]
Well for the last 20 days or so the bot included the final upvote count in its return response, and we keep that reponse ID in the db already, so it should be fairly easy to retrieve that reponse and parse the final upvote count out of it. But for earlier investments, yeah, we'll have to do some sort of estimation I think.

**Comment by rickles42** [comment]
Working on this. My script is quite slow because it requires Reddit API usage, so it'll take another day or two. I'm about 15% complete so far haha

**Comment by rickles42** [comment]
Done. The `initial_upvotes` column is populated for 95% of investments, going back to when we first started including the final upvote count in the bot responses. If we want to backfill the remaining 5% we'll have to do some sort of estimation, either time-wise like robalb suggests above, or by reversing the return formula (neither will be precise).
