### ISSUE TITLE
Seems like link to source code goes to a different bot

### ISSUE THREAD

**Issue by brynhayder** [thecsw/memeinvestor_bot#2]
https://github.com/thecsw/memeinvestor_bot/blob/master/src/message.py#L9

**Comment by thecsw** [comment]
Oops, thanks!
The issue is fixed.
Check the link below for the commit fixing the issue!
[Fix](https://github.com/thecsw/memeinvestor_bot/commit/a170be58b2e36e2ff702e205e116af9edbe1b3dd)
