### ISSUE TITLE
API should support bulk requests so we can generate historical charts with one call

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#202]
Currently the website has to make separate requests for each day of data in the front page historical charts. For simplicity let's have the API return multiple days in a single request.

**Comment by rickles42** [comment]
(We need this more than ever now that we're showing several weeks of data on the chart, instead of just a few days.)

**Comment by thecsw** [comment]
This is an old issue. New API suuports very fast parallel operations which makes the huge queries possible.
