### ISSUE TITLE
Add historical investor net worth chart to profile page

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#205]
It would be great to show a historical chart of user's net worth over the course of a season. I think this may have been proposed before but most recent proposal from [here](https://www.reddit.com/r/MemeEconomy/comments/91ivxp/meme_investments_status_update/e2yw32c).

**Comment by thecsw** [comment]
We have charts and graphs implemented. Closing this issue.

**Comment by robalb** [comment]
This was a request for a set of data that we are not showing in the charts at the moment, but #202 should be implemented first in order to calculate this data efficiently, or we would need to make some changes to the api
