### ISSUE TITLE
add secure headers to the website

### ISSUE THREAD

**Issue by robalb** [thecsw/memeinvestor_bot#214]
we shoud add some basic security headers to the website.
This is a list of the main headers, an analysis of the website security can be found [here](https://securityheaders.com/?q=memes.market&hide=on&followRedirects=on)

      header / {
         # Enable HTTP Strict Transport Security (HSTS) to force clients to always
         # connect via HTTPS (we may have to discuss this)
         Strict-Transport-Security "max-age=31536000;"
         
         # Enable cross-site filter (XSS) and tell browser to block detected attacks
         X-XSS-Protection "1; mode=block"
         
         # Prevent some browsers from MIME-sniffing a response away from the declared Content-Type
         X-Content-Type-Options "nosniff"
         
         # Disallow the site to be rendered within a frame (clickjacking protection)
         X-Frame-Options "DENY"
         
         #strip any path information from the referrer information when navigating to other urls
         Referrer-Policy "strict-origin"
         
         #restrict the use of the following features to js
         Feature-Policy "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
         
         #defines approved sources of content that the browser may load.
         #'-Report-Only' mode won't apply the policy, but just report blocked resources in the console
         #once the policy have been tested, the '-report-only' suffix can be removed, leaving only 'Content-Security-Policy'
         Content-Security-Policy-Report-Only "default-src 'self';script-src 'self' cdnjs.cloudflare.com;style-src 'self' cdnjs.cloudflare.com fonts.googleapis.com;font-src 'self' cdnjs.cloudflare.com fonts.gstatic.com fonts.googleapis.com; upgrade-insecure-requests"
      }

it may also be a good idea to register an account on https://report-uri.com/
and add the `report=https://...the-report-uri-account-url` directive to the `X-XSS-Protection` header
and the `report-uri https://...the-report-uri-account-url` directive to the `Content-Security-Policy` header

**Comment by keanucz** [comment]
I'm not sure whether we should enable HSTS, as anything to do with HTTP/HTTPS is a bit fiddly and we need to consider whether we're able to drop HTTP support or not. All the other options though look to be good, and should be implemented.
