### ISSUE TITLE
User entry shouldn't appear so high on page. [Web]

### ISSUE THREAD

**Issue by ilikealotgithub1234** [thecsw/memeinvestor_bot#243]
<img width="207" alt="screen shot 2018-10-03 at 6 09 29 pm" src="https://user-images.githubusercontent.com/17275744/46442461-b6467680-c737-11e8-8927-b2bcdb642b57.png">
<img width="241" alt="screen shot 2018-10-03 at 6 09 52 pm" src="https://user-images.githubusercontent.com/17275744/46442462-b6467680-c737-11e8-973d-c07c17f93902.png">
<img width="1675" alt="screen shot 2018-10-03 at 6 11 35 pm" src="https://user-images.githubusercontent.com/17275744/46442488-cbbba080-c737-11e8-8777-f047baa52c2b.png">

**Comment by thecsw** [comment]
Yep, that's right. We had this issue before, seems that it has not been fixed since. I will forward this to the front-end team. The issue will be open until the issue is fixed. Thanks!

**Comment by robalb** [comment]
Hi @ilikealotgithub1234 could you tell me your user agent? Something like the type of browser and os you have would be very useful for debugging the problem

**Comment by lynnpark** [comment]
I'm seeing the same problem on Chrome on Windows 10
