### ISSUE TITLE
calculator not working in Samsung browser

### ISSUE THREAD

**Issue by ghost** [thecsw/memeinvestor_bot#246]
the estimate is struck at 000 and doesn't change whatsoever. working fine in other browsers. i think it is a browser compatibility issue

**Comment by thecsw** [comment]
This is probably a front-end issue. I will forward this to the front-end team. The issue will remain open until the issue is solved or another solution is reached. Thanks!

**Comment by thecsw** [comment]
I think this issue was because we were calculating remotely. With #269 the calculator works in the browser and I would assume that it ultimately solves the issue. Thank you.

**Comment by robalb** [comment]
No, i think this had to do with caching or es6 js compatibility issues, i experienced similar problems on old samsung browsers. The solution here would be for me to actually learn how to use webpack and integrate it, that would solve both the caching and incompatibility issues in a more professional way that the one we are currently using. Either way, i see no reason to keep this issue open, there already is one regarding the compatibility stuff
