### ISSUE TITLE
Ability to Short Memes

### ISSUE THREAD

**Issue by lynnpark** [thecsw/memeinvestor_bot#250]
There needs to be an ability to short memes. The less upvotes a meme earns, the higher the resulting payoff.

**Comment by jimbobur** [comment]
This has been discussed previously on several occasions and the conclusion was reached that it wouldn't be a good idea. If a bad meme is posted, it's likely to just stay at or close to zero upvotes. If it's already got sufficiently high upvotes that you could theoretically make a profit by shorting it, it's clearly already a good meme that's only going to increase in upvotes. So whilst you could theoretically implement this, there wouldn't be much point in it; you'd pretty much always lose coins. 

For previous discussion of the topic, see closed issue #26

**Comment by thecsw** [comment]
Closing this issue. Thanks, @jimbobur
