### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OofYeetMcGee** [thecsw/memeinvestor_bot#26]
!short AMOUNT

To short bad memes

**Comment by robalb** [comment]
What do you mean?

**Comment by thecsw** [comment]
Do you want to bet against memes?

**Comment by jimbobur** [comment]
In theory this could be achieved by making the shorted return:
 return_short = investment * multiplier_calculate( - change_in_upvotes )
 i.e the same return function behaviour but gaining you coins if the meme upvotes count decreases.
  
**HOWEVER**: If a bad meme is posted, it's likely to just stay at  or close to zero upvotes. If it's already got sufficiently high upvotes that you could theoretically make a profit by shorting it, it's clearly already a good meme that's only going to increase in upvotes. So whilst you could theoretically implement this, I'm not convinced there'd be much point in it; you'd pretty much always lose coins.

**Comment by thecsw** [comment]
btw, bot is running!

**Comment by OofYeetMcGee** [comment]
Why not double the reward for shorting as it's clearly a high risk maneuver?

**Comment by thecsw** [comment]
Just explain the whole thing and we will think about it

**Comment by OofYeetMcGee** [comment]
The basic idea is to be able to bet against memes. While this does indeed sound crazy, as posts usually only go up or flatline at only a few upvotes, it would be interesting if there was the ability to bet against posts you feel are going to get downvoted. Since shorting is much more risky than typical buy options, dev might consider rewarding shorts by a higher factor. It would also add an incentive to downvote bad posts, making posting riskier as well.

It would add a different dynamic. Just an idea though

**Comment by thecsw** [comment]
Dev team discussed this and we think this is a bit unnecessary at this stage of MemeInvestor. Sure, the idea is good but Reddit doesn't have a -100 downvoted memes. It doesn't work on the platform so smoothly as it works in real life. For now, I will close this issue. If somebody can correct me or change my mind, please do!

Sincerely,
thecsw
