### ISSUE TITLE
ROI Calculator rounds up

### ISSUE THREAD

**Issue by matthewsanetra** [thecsw/memeinvestor_bot#260]
Banks usually always round down.

**Comment by thecsw** [comment]
Can you please elaborate and add more information? Like images or actual examples of your issue.

**Comment by matthewsanetra** [comment]
This seems to be a front end issue, as I’m pretty sure the API only returns a multiplier/factor.

If you type in old 1, new 100, as it is already maxed out, it should be the same as old 1 new 1000.

However, new 1000 actually produces less than 10*new100 showing that new 100 was rounded upwards after the multiplication of the factor

**Comment by thecsw** [comment]
Can you elaborate more? Do you mean that the calculator on memes.market does not follow the algorithm described in our white paper or is it a precision issue?

**Comment by matthewsanetra** [comment]
#269 seemed to solve this
