### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by thecsw** [thecsw/memeinvestor_bot#272]
I had this recommendation a long time ago and I think this is the moment where we need to make some test cases for the bot.

**Comment by mappum** [comment]
Totally agree, development could be made a lot easier without having to test by hand on Reddit. Would be nice to be able to mock the Reddit API types (`Submission`, `Comment`, etc.), and the database (or at least use a throwaway test database in the tests) to test the core command handling behavior.

**Comment by thecsw** [comment]
Absolutely!
