### ISSUE TITLE
Make a single top level comment on all /r/MemeEconomy posts, and only parse commands that are a reply to it

### ISSUE THREAD

**Issue by agincel** [thecsw/memeinvestor_bot#30]
/r/MemeEconomy comment threads have become littered with MemeInvestor Bot commands. The easiest way to circumvent this is to have the bot add a single comment upon the posting of a new thread, and to only listen for/respond to commands that are in reply to that comment. (Effectively, just check that a comment is replying to any comment made by the bot).

This will greatly improve the /r/MemeEconomy browsing experience while giving the added benefit of keeping all MemeInvestor commands in a single place.

**Comment by thecsw** [comment]
We already have the feature implemented but it is not active!
We are waiting for mods' approval.
