### ISSUE TITLE
Suggestion: Add inside trading penalty

### ISSUE THREAD

**Issue by robalb** [thecsw/memeinvestor_bot#31]
As some redditors have pointed out, insider trading ( investing in your own meme) can be a serious issue, and should be penalized with a profit reduction in case of  succesful investment

**Comment by thecsw** [comment]
Wil do! I will update when I'm done implementing this!

**Comment by thecsw** [comment]
Hey! I added a feature that does not allow insider trading! No penalty for now, just not allowed.

[Commit](https://github.com/thecsw/memeinvestor_bot/commit/f1c99069780cd37107dafefa16109d3461038cbf)
