### ISSUE TITLE
Big flaw in investment algorithm

### ISSUE THREAD

**Issue by sezze** [thecsw/memeinvestor_bot#32]
Currently the "x" variable in the algorithm for the return is an absolute change in upvotes. This creates problems. If I invest in something with 1 upvote I am risking a lot, no one knows what will happen, pretty good if it then ends up at 1000 upvotes after 4 hours. On the other hand if there's a post with 100k upvotes, it's pretty much guaranteed that it will gain more than just 1000 additional upvotes in 4 hours, why wouldn't it? It's already at 100k. In these examples I feel like the first investor should get about a 10x return on his investment and the second investor should gain pretty much nothing, probably in fact lose half of his/hers investment as it gained only a 1% increase in upvotes. The return should be a mix of absolute change and percentage based change.

**Comment by thecsw** [comment]
As a fix, I will just multiply the formula by an inverse-square to the power 10. This *new* formula will favor the small initial upvotes. Surely, in the future, we can come up with better ideas!
