### ISSUE TITLE
love the idea - just want to suggest a term

### ISSUE THREAD

**Issue by calchulus** [thecsw/memeinvestor_bot#324]
I'd love to just create the term Invest**meme**nts

Cheers <3

**Comment by thecsw** [comment]
Do it.

**Comment by nithssh** [comment]
lol just did a quick "Find" on the entire solution and there are at least 142 occurrences within 29 files.

that's just whole word matches...  given the current status of the project i doubt anyone might be ready to do such a "small" yet HUGE change for a tiny joke even tho we all might love the idea of it sadly.

**Comment by thecsw** [comment]
I agree with @Dem1se. Closing the issue.
