### ISSUE TITLE
Ignore commands that are not replies to top level comment

### ISSUE THREAD

**Issue by TwiN** [thecsw/memeinvestor_bot#36]
As mentioned in #30, commands that are not replies to the top level comment should be **completely** ignored.

That way, not only can the bot be improved (only check for replies of top level comment rather than all comments), it will be future-proof as [some users will eventually complain](https://www.reddit.com/r/MemeEconomy/comments/8msuyv/this_format_can_work_for_a_variety_of_things_a/dzq3zru/) about the fact that all the `!invest`, `!balance`, `!create` commands are ruining the comment section of the subreddit.

**Comment by thecsw** [comment]
Yes, it will be added tomorrow, I guess. Only commands replied to our anti-spam message will be parsed.

**Comment by rickles42** [comment]
Unless I'm mistaken, this is addressed by main.py line 76, which attempts to ensure that only direct replies to the bot are processed:

`comment.parent().author.name != config.username`

**Comment by thecsw** [comment]
This is true. Only direct replies will be processed.
