### ISSUE TITLE
Firms with no users are still appearing in API

### ISSUE THREAD

**Issue by patrickblackjr** [thecsw/memeinvestor_bot#361]
![Image from iOS (1)](https://user-images.githubusercontent.com/13282318/54801452-ef669a80-4c34-11e9-9863-9cf211677d61.png)

This might represent a larger issue: firms with no users persist in the database even after no users are in the firm. This would also prevent anyone from ever creating another firm called the same as an abandoned firm.

This also brings the question: Should we be deleting firms whose users have been inactive for a set period of time to prevent claiming of firm names or just general stagnation?

**Comment by thecsw** [comment]
Fixed!
