### ISSUE TITLE
Command `firm <firmname>` doesn't work

### ISSUE THREAD

**Issue by thammarith** [thecsw/memeinvestor_bot#363]
**Describe the bug**
I tried to get the information of a firm using the command `firm <firmname>` but it doesn't work. I also tried `!firm <firmname>`; it also doesn't work. The bot doesn't reply to me. Tried both direct reply to the bot, and on a child reply.

**To Reproduce**
1. Comment `firm The Federal Reserve Dank` or `!firm The Federal Reserve Dank`

**Expected behavior**
The bot should reply me with the info of the firm

**Screenshots**
![image](https://user-images.githubusercontent.com/8011543/54806414-7dca3300-4cac-11e9-8b96-ec41789e13f9.png)

![image](https://user-images.githubusercontent.com/8011543/54806425-81f65080-4cac-11e9-8a6c-81aa4ab5a1a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Firefox
 - Version: 66.0

**Additional context**
- Comment that I tried with [`firm The Federal Reserve Dank`](https://www.reddit.com/r/MemeEconomy/comments/b3s1em/cars_antman_v_thanos_guaranteed_profits_invest/ej3ofav/?context=3)
- Comment that I tried with [`!firm The Federal Reserve Dank`](https://www.reddit.com/r/MemeEconomy/comments/b3s1em/cars_antman_v_thanos_guaranteed_profits_invest/ej3ofmg/?context=3)

**Comment by hazzakak** [comment]
Is this fixed as there was a recent commit about the firm command?
EDIT: Tagged owner
@thecsw

**Comment by keanucz** [comment]
Yes, this is fixed already as far as I can see. 

![SOL Enterprises](https://i.imgur.com/x7X7hKN.png)

**Comment by thammarith** [comment]
> 
> 
> Yes, this is fixed already as far as I can see.
> 
> ![SOL Enterprises](https://camo.githubusercontent.com/3dc04d9101db806e409969f849b8301054211110/68747470733a2f2f692e696d6775722e636f6d2f78375837684b4e2e706e67)

Thanks! I'll close this.
