### ISSUE TITLE
Add command to report unprocessed investment

### ISSUE THREAD

**Issue by TwiN** [thecsw/memeinvestor_bot#38]
Some people have investments that are still unprocessed (e.g. [me](https://www.reddit.com/r/MemeEconomy/comments/8msuyv/this_format_can_work_for_a_variety_of_things_a/dzrr60r/?context=3))

![](https://twinnation.org/api/screenshots/2018-05-29_134246.png)

The command would force the bot to read the previous investment comment it posted, and update it accordingly.

I am aware that this is no easy command to add, but having a command like `!fixinvestment` is significantly easier than having to re-process all comments.

I'm not sure if this has happened to others, but it has happened to me on several occasions.

**Comment by thecsw** [comment]
Hey! No need for that. The "unreturned" investments were just a 1 day issue with our new codebase. It has been fixed. The system automatically checks for investments that need to be evaluated and it can't miss that. 

Happy investments!
