### ISSUE TITLE
Networth reported in firm api is not correct

### ISSUE THREAD

**Issue by thomasvt1** [thecsw/memeinvestor_bot#384]
**Describe the bug**

**To Reproduce**
1. Go to 'https://meme.market/api/firm/158/members?per_page=100&page=0&from=&to='
3. Scroll down to 'networth'
4. See the number: 0

**Expected behavior**
networth should never be zero (except if user is broke)

**Screenshots**
![image](https://user-images.githubusercontent.com/2271011/57575077-45410d00-7444-11e9-9503-a14c99e3f209.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Any
 - Browser [e.g. chrome, safari]: Any
 - Version [e.g. 22]: Any

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: Any
 - OS: [e.g. iOS8.1]: Any
 - Browser [e.g. stock browser, safari]: Any
 - Version [e.g. 22]: Any

**Additional context**

**Comment by thomasvt1** [comment]
The problem is that if I want to make a leaderboard containing only my firm I have to make a very large amount of calls (size of firm + 1). So for SOL that would be 41 API calls instead of just one;

![image](https://user-images.githubusercontent.com/2271011/57575096-a4068680-7444-11e9-92d0-47df25b757a8.png)

**Comment by keanucz** [comment]
Is the user's networth actually 0? Also, would you expect broke to be 1 if their networth is below 100? I could probably throw in a quick PR for that.

**Comment by thomasvt1** [comment]
@Keanu73 networth is wrongly reported as balance it seems?

Networth isn't actually 0 but somehow it is reported as zero.

Networth is calculated here;
https://github.com/thecsw/memeinvestor_bot/blob/master/api/firm/firm.go#L187

**Comment by keanucz** [comment]
I mean, doesn't networth == balance?

**Comment by thomasvt1** [comment]
Nope, your balance is the amount you can invest, and create a firm with.
Net worth is ``balance + active investments``.

If someone has done !invest 100% the balance should be zero and the net worth should be equal to the investment done

**Comment by keanucz** [comment]
It's kindof hard to read that SQL query so I'm not sure what else we can do lol

**Comment by thecsw** [comment]
Good point! I completely missed it. Networth was never even supposed to be there. I will make a PR to get rid of it.
