### ISSUE TITLE
Automatic badge granting?

### ISSUE THREAD

**Issue by keanucz** [thecsw/memeinvestor_bot#398]
Badges like the Contributor badge or Donor badge have to be granted manually, but what if we could just do 2 OAuth callbacks (e.g. for Contributor badge: github and reddit), and then grant the user their supposed badges?

**Comment by thecsw** [comment]
That is a good idea. For now, we have around 20 contributors and 14 patrons. And that happened over the year. It surely would be great to automate it, but it still can be done manually. If we had thousands of users, it would be a high priority. If you feel like doing it, please do.
