### ISSUE TITLE
Change graph for Step 1 on the README

### ISSUE THREAD

**Issue by ometrist** [thecsw/memeinvestor_bot#48]
As the current graph with the blue line looks outdated, I decided to make a new graph that compliments what's already present on the README. 

I recommend using the graph below, or make a different one of course if you want. I'd love to help you guys out more with what you need but I know nothing about coding/programming. You guys are doing God's work here 😄

![j0u2gzp](https://user-images.githubusercontent.com/39782752/40822835-d9242034-6522-11e8-89b9-a3ec49982025.png)

**Comment by rickles42** [comment]
+1 for using Comic Sans

**Comment by ometrist** [comment]
my computer is calling the font "Chalkboard" but it does look like Comic Sans lol, you can pick any font you want and i'll change it

**Comment by jimbobur** [comment]
I like this graph, the comic sans adds character :smile: . I was thinking about replacing the first graph with something like this before I went to bed last night. What software did you use to produce it?

**Comment by ometrist** [comment]
Whatever's pre-installed on my MacBook... "preview" and I used some random website to make the initial graph. I can't remember the exact website. Want me to make more stuff? You let me know

**Comment by jimbobur** [comment]
Have added a pull request to the project with a different bot comment update for when a user breaks even. Once it's approved we can add this graph to the readme.

**Comment by jimbobur** [comment]
Have pushed @ometrist 's graph to a new branch and opened a [new pull request](https://github.com/MemeInvestor/memeinvestor_bot/pull/59)
