### ISSUE TITLE
Suggestion: Decouple the bot's input loop from its output loop

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#52]
Currently, the bot only processes new commands and updates the game state as fast as it can output the results. (Said differently, its input loop, game state loop, and output loop are all closely coupled.) The bot could be made more flexible and responsive if these loops were decoupled: allow the input loop to process commands and update the game state in real time, while the output loop is responsible for independently reading the game state and posting updates on Reddit (the slow part). This would also free up the system to support additional output loops (like a website) that can run independently and be updated in real time.

**Explanation**: (I'll focus on the input loops in main.py, although this all applies similarly to calculator.py.) Currently, the processing loops post comments synchronously. This means that the loop cannot continue until the posted/edited comment goes through, limiting throughput to one processed command per second. (I'm assuming the bot is still limited to one post or edit per second; please let me know if that's inaccurate.)

A decoupled design would have the input loop read comments, process commands, and update the database in real time. However, actually posting the results to Reddit would be the work of an output loop running separately. At first, this output loop should probably just makes direct replies like the bot does today. But with a decoupled design we have the flexibility to make the output loop, say, provide batched investment summary posts instead of direct replies (to help with posting limits).

This is obviously a major refactoring job, but I think it will be necessary to keep up with demand and also to provide other interfaces (output loops) to the game state.

**Comment by spreadneck** [comment]
Could this output loop just be another bot?

**Comment by rickles42** [comment]
Yes, in theory. But notice that the input loop wouldn't actually post to Reddit at all, so it might be more accurate to say that the output loop is the _only_ Reddit bot in this configuration. (The input loop does have to monitor Reddit and modify the database, but I don't know whether people would consider that set of functionality a "bot" exactly.)

**Comment by thecsw** [comment]
Hmmm. We will think about it. For now, the bot is operating normally and sometimes too fast because we hit the Reddit posting limits. We will examine this option!

**Comment by rickles42** [comment]
I asked users about the tradeoffs of this decoupled approach and so far the response seems in favor:

https://www.reddit.com/r/MemeEconomy/comments/8pcrwp/about_the_delays_clients_connecting_via_oauth2/e0a8p3h/

**Comment by nickmahdavi** [comment]
Perhaps consider decoupling these processes into _two_ bots? I can understand if this would be troublesome and too hard to work with. But if the latency problems end up having to do with the reddit APIs and the fetch limits, you could have the bots work together. Have one bot scrape MemeEconomy (read) and the other post (write), saving requests and speeding up the process.

This could prove troublesome, though, if both accounts are banned for "circumventing Reddit's limits".

**Comment by rickles42** [comment]
@qwertios What you describe is technically possible, but Reddit's rules discourage that behavior. It's a little bit of a gray area, but the idea is that every bot should keep its Reddit requests to a certain volume. Simply redefining our bot as a collection of bots _would_ increase our total allowed volume of Reddit requests, but I think it goes against the spirit of Reddit's API rules.

**Comment by rickles42** [comment]
Now that I've spent a long time with the Reddit APIs and our Reddit library `praw`, I think I've come to believe that, in fact, decoupling our input and output loops would _not_ help our throughput very much. Back when I originally wrote this suggestion, I was under the impression that reads and writes were treated differently by Reddit. However, in fact they are equivalent---the limit is on API calls, whatever type they may be.

With that in mind, letting our input loop spin fast instead of blocking on writes, like I had originally envisioned, is not actually possible---read calls to the Reddit API are also blocking.

Decoupling the two _might_ be able to win us a bit of responsiveness in terms of how fast the game state reacts to new requests, but it would be at the cost of reply latency and likely not a big win in any case. The best approach to improvement, I believe, is finding ways to reduce the number of API calls the bot needs to make, for example by caching certain information.
