### ISSUE TITLE
Bot should be easier to configure and deploy from scratch in a test environment

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#53]
Ideally a new developer should be able to install Docker, clone the repo, and run a single command to spin up a "dummy" version of the bot.

The dummy wouldn't need to have full functionality (like actually monitoring or posting to Reddit) but it should spin up a real database instance (probably empty). It should probably accept commands via stdin and print replies and output via stdout - enough functionality that devs can use it to validate certain changes easily.

**Comment by rickles42** [comment]
I can try tackling this issue this weekend. I think the work breaks down into the following pieces:

1. Refactor main.py into two loosely-coupled parts: the game state and the input loop ("driver"). Now a Python loop that monitors Reddit comments can be thought of as just one possible driver. A simple command-line-based loop can be used as the default (dummy) driver.

2. Refactor main.py's output to be decoupled from the game state as well. Now a Python loop that posts replies to Reddit can be thought of as just one possible output loop. A simple command-line-based loop can be used as the default (dummy) output loop.

3. Make main.py use the dummy driver and dummy output loop by default.

4. Refactor config.py, Dockerfiles, and docker-compose.yaml so that the default (test) deployment "just works." It will use dummy loops and shouldn't require Reddit bot credentials or any manual configuration.

**Comment by thecsw** [comment]
Yeah, the bot deployment is not very user and newbie friendly right now. The documentation and maybe wiki page is in development rn. We will publish new instruction, hope it can make everything clearer

**Comment by rickles42** [comment]
I'm currently working on this. I hope to have an easily-deployed dummy bot ready this weekend.

**Comment by rickles42** [comment]
This rewrite is going to be more extensive than expected. I might have to start smaller and make baby steps.

**Comment by dzervas** [comment]
Hey, just keep in mind that unix sockets are fairly fast and can probably be used for IPC between the reddit consumers (submitter, main & calculator) and the provider. Just throwing ideas...

**Comment by rickles42** [comment]
One thing that would help make the bot easier to launch from scratch would be consolidating environment variables and adding explanations for all of them. I opened Pull Request #72 to do just that if anyone wants to check it and merge.

By the way, does anyone have a full list of the steps for setting up and running the bot? Once all the necessary files are in ${VOLUME_ROOT}, does it just take a docker-compose run?

**Comment by thecsw** [comment]
Okay, #72 closes this issue. Thanks for your contribution!

**Comment by rickles42** [comment]
@thecsw Please re-open this issue; I don't think it's fully resolved yet. (And I can't figure out how to re-open it myself haha.)

A couple tasks left before I would say running the bot is truly friendly to new contributors:

- Need to remove dependency on ${VOLUME_ROOT} or else have @dzervas provide instructions for populating it

- Basically, make it so that literally the only thing someone needs to do after cloning is fill out .env and then use `docker-compose up`

**Comment by dzervas** [comment]
the VOLUME_ROOT is an empty directory. could be anywhere. You can default it to a got ignored non existing folder in the repo.

**Comment by rickles42** [comment]
Even though a dummy bot that doesn't require Reddit access might still be convenient, I think the whole project is now fully deployable locally, from scratch, by only cloning and editing .env.
