### ISSUE TITLE
!top command doesn't line-break correctly

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#56]
See the example response here:
https://www.reddit.com/r/MemeEconomy/comments/8o173y/meme_wars_the_bot_awakens/dzzw5fz/?st=jhxmedmk&sh=1d68ad6a

**Comment by thecsw** [comment]
Yeah, this is an issue for desktop clients! I will review the pull request! Thanks

**Comment by thecsw** [comment]
Thanks, your pull request #57 has been merged!
