### ISSUE TITLE
Wire funds/transfer investments

### ISSUE THREAD

**Issue by kerv17** [thecsw/memeinvestor_bot#65]
Sell risky investments to other investors to make it a more realistic market

**Comment by ometrist** [comment]
this seems like a lot of work to write code for that I think isn't too worthwhile to do, I'd honestly be okay not having this feature at all

**Comment by thecsw** [comment]
Hi, if you mean transfer investments, that's really not needed! And it is also quite pain in the ass to implement. However, we can make a `!send` command that can transfer funds from one account to another. For example, if I write `!send 100 thecsw`, it will send 100 memecoins to thecsw if he has an account. This is possible. If you want to talk about this feature, please open another issue. I need to close this one as it is rejected. Thanks
