### ISSUE TITLE
Suggestion: !leaderboard command to show users with the highest balances

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#7]
Could be fun for people to be able to see, for example, the top 10 balances (and associated usernames)

**Comment by thecsw** [comment]
Nice feature. I thought about getting the bot a website or another script to do it. I will work on it!

**Comment by thecsw** [comment]
Accidentally closed the issue.

**Comment by rickles42** [comment]
Submitted new PR for this using the new codebase and addressing the feedback from the first PR.
