### ISSUE TITLE
Going to Gitlab?

### ISSUE THREAD

**Issue by thecsw** [thecsw/memeinvestor_bot#71]
We all  know that Microsoft has very aggressive business strategy. Remember Skype, Nokia, LinkedIn, Minecraft and etc.? Let's migrate to Gitlab!

**Comment by rickles42** [comment]
Right now GitHub is the best place for collaborative coding. I suggest waiting until Microsoft actually does something to harm GitHub before jumping ship, otherwise you're just adding unnecessary chaos to the project.

Full disclosure: I'm a Microsoft employee 😄

**Comment by TwiN** [comment]
@thecsw I don't think there's a need to migrate this early, Microsoft hasn't acquired GitHub yet. The deal should close by the end of the year according to [Microsoft's article](https://news.microsoft.com/2018/06/04/microsoft-to-acquire-github-for-7-5-billion/):

> Subject to customary closing conditions and completion of regulatory review, the acquisition is expected to close by the end of the calendar year.

Though it is up to you, the repository is yours.

**Comment by thecsw** [comment]
Okay, for now.
