### ISSUE TITLE
Deploying the bot should create an empty database if no database exists

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#73]
The code today depends on the existence of a pre-initialized database, which makes it difficult to do your own test deployment from scratch.

If someone who understands SQLAlchemy could update the project to handle the case when no Investor or Investment tables exist (at least when DRY_RUN is enabled), that would be super helpful.

**Comment by rickles42** [comment]
Alternatively, someone could just check in a script that initializes an empty database offline, along with instructions to put that database into the right spot to be used by a deployment. (This would just add a couple configuration steps to the README which is fine for now.)

**Comment by thecsw** [comment]
`CREATE TABLE Name IF NOT EXISTS`

**Comment by thecsw** [comment]
Okay, we will get on it

**Comment by rickles42** [comment]
I think I figured out how this can be accomplished with SQLAlchemy's `Base.metadata.create_all` function. Working on a fix for this issue today. Should make from-scratch setup much easier.

**Comment by rickles42** [comment]
Okay, I have a pull request ready for this that automatically initializes the database. But it's built on top of pending pull request #72. To reduce the chance of confusion I'll wait for #72 to be merged first.

**Comment by dzervas** [comment]
Hit it

**Comment by rickles42** [comment]
Much appreciated!
