### ISSUE TITLE
How is the initial growth factor of a post calculated when the initial score is 0?

### ISSUE THREAD

**Issue by GhostBetta** [thecsw/memeinvestor_bot#76]
From the formula on your website, it looks to be impossible to calculate the return on an investment on a post that started with 0 upvotes, as it would require to divide by zero. However, having invested in a post with 0 upvotes myself, I know this not to be true.

Is there some other way to calculate the initial growth factor of a post when it has a score of 0 points?

**Comment by jimbobur** [comment]
Well-spotted. In the case of `u_init = 0`, the denominator is set to 1 to avoid this DIV0 error, so relative change in upvotes is simply calculated as: `x=1+(u_final-u_init)/1 = 1+u_final`.
