### ISSUE TITLE
Suggestion: Add cosmetic reward for users who have never gone bankrupt (or cosmetic punishment for users who have)

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#8]
(Totally up to you what direction you want to take your bot--just throwing this possible feature out there.)

It could encourage high-quality investment decisions if, for example, users who have gone bankrupt 3 times have a little [3☠] added to their messages. Or, on the flip side, maybe users who have never gone bankrupt could get a little [💰] added to their messages.

**Comment by thecsw** [comment]
To do so, I should talk with r/MemeEconomdy mods.
I will consider this, thanks!

**Comment by rickles42** [comment]
I like the idea of implementing this as user flair (which, as you say, would require mod support) but you wouldn't necessarily have to do that - I was really just thinking the bot could include the cosmetics in the responses it makes to users. So for example, if a user with 2 bankruptcies uses !balance, the bot could add [2☠] to the end of the balance statement.

**Comment by TwiN** [comment]
@jimbobur was this added with the above commit?

On the index page, "top investors" section:

> A red badge next to the username indicates the number of times the user went bankruptcy. 

Shouldn't this issue be closed, then?

**Comment by ometrist** [comment]
since so few people go bankrupt, can we close this issue whether it is solved or not @TwinProduction & @rickles42 ? I don't see much value in making a flair for those who go bankrupt since there are so few people who do, and they probably don't want to be shamed publicly. I also don't see much to gain in giving users a flair who have never gone bankrupt because almost everyone has never gone bankrupt. 

Your thoughts?

**Comment by rickles42** [comment]
Closing is fine with me as well - it's okay if the suggestion didn't get enough support to become a reality. And the !top command and website leaderboard do satisfy a bit of people's competitiveness anyway.

**Comment by thecsw** [comment]
I talked with the mods of r/MemeEconomy. We can't do cosmetic rewards on reddit but we can do them on memes.market. When the database is rebooted, investors with >1bil will receive some cosmetic rewards for their first season. I will close this issue for now. Thank you!
