### ISSUE TITLE
Some website css and functionality

### ISSUE THREAD

**Issue by thecsw** [thecsw/memeinvestor_bot#80]
Firstly, the search bar is a bit too high. At least for me.

Secondly, the search is working only when I press the arrow icon. Isn't more intuitive to press ENTER?

Thanks. 

![deepinscreenshot_select-area_20180606144701](https://user-images.githubusercontent.com/16922860/41033760-a77e5dae-6998-11e8-9bef-e3b63ea11c6e.png)

**Comment by robalb** [comment]
@thecsw The search bar thing is a bug. What browser on what device are you using? This search bar was already integrated in the nav in the first release of the website, before being removed. Did it have the same problem back then, if you noticed it?

**Comment by thecsw** [comment]
I use chromium, lemme try with surf

**Comment by thecsw** [comment]
Interesting, works nice with surf. Maybe just a browser issue? 

![deepinscreenshot_select-area_20180606170617](https://user-images.githubusercontent.com/16922860/41039933-0143ff20-69ac-11e8-8485-21d9df6e807f.png)

**Comment by robalb** [comment]
Yeah. Can you sen me your useragent data? Private chat if you prefer

**Comment by thecsw** [comment]
How to do I do it exactly?

**Comment by robalb** [comment]
Write `console.log(navigator.userAgent)`

In your browser console

**Comment by robalb** [comment]
i added the enter key feature btw

**Comment by thecsw** [comment]
Yeah, saw that! Thanks!

**Comment by thecsw** [comment]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

**Comment by thecsw** [comment]
Thanks!

**Comment by robalb** [comment]
So it's fixed now?
