### ISSUE TITLE
Statue of limitations

### ISSUE THREAD

**Issue by NelsonZC** [thecsw/memeinvestor_bot#86]
9 house after the command the bot finally replied. I can see this being a problem if someone invested and it took too long.
Proof: https://imgur.com/a/BiScB9g

**Comment by rickles42** [comment]
@dzervas Could this be a result of your switch from monitoring the subreddit comment stream to monitoring the bot's inbox? Specifically, if the bot is down for some time, then comes back up, will it work its way through old comments in its inbox?

**Comment by dzervas** [comment]
Yes it is 😢
I’m almost sure it’s due to reddit API returning the newest and not oldest comments

**Comment by hipp013** [comment]
Yeah, this actually happened today, someone invested around 300000 coins and had the investment go in hours later, causing them to lose about 178000 coins.

**Comment by rickles42** [comment]
Then I guess one quick fix would be to switch back from inbox-monitoring to comment-stream monitoring and restart the monitoring process. (Although if the bot has already finished processing its whole inbox, I guess that would make it current now.)

Longer term, we can reduce the latency of the bot with a variety of changes, but I still would like us to do some measurement first so we know more specifically what we need to go after.

**Comment by hipp013** [comment]
I would say even if you do switch back to comment-stream monitoring, maybe consider an additional check that cancels the investment if the !invest comment is over 60 minutes old.

**Comment by dzervas** [comment]
The performance gain is way too high to go back...
I’m sure that reddit has a parameter to order them. I just don’t have the time right now to research it

**Comment by rickles42** [comment]
I've made a quick fix to ignore stale requests (i.e. requests older than a certain threshold). That will prevent more people from getting screwed by the slow bot.

Long term, of course, it would be best to improve throughput so that all commands can be processed within a minute or two. We're working on that separately.

**Comment by rickles42** [comment]
@thecsw @NelsonZC I believe this issue can be closed now that @thecsw merged #88 (assuming he rebooted the bot to use that merged code, of course). The bot should no longer process requests older than 15 minutes.
