### ISSUE TITLE
Reduce latency of bot replies

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#87]
After our conversation the other day about performance, I went ahead and did some rudimentary measurements. More work to be done of course, but this is a starting point.

**tl;dr**: We do appear to have a latency problem (i.e. the bot takes too long to reply to commands) but also there is some weird resetting pattern that I can't explain. There have been a variety of proposals to reduce latency, we'll need to look into which ones make sense.

I wrote a simple script to monitor the bot's posts and compare their timestamps to the timestamps of the posts the bot was replying to. I can't be sure my script was bug-free but I did some sanity checks and it appears to be accurate. Here are the results:

![untitled](https://user-images.githubusercontent.com/81503/41126444-5d3b2618-6a5c-11e8-8df9-6c5a7f16e87a.png)

(Each bar in the chart is one response from the bot. The height of the bar is the time, in seconds, between the command and bot's reply. This was looking at replies the bot made from about noon-1 Pacific time today.)

**First thing to notice**: Latency gets very bad. The bot is regularly taking over 10 minutes to reply to commands. So there's a problem to be solved.

**Second thing**: Latency consistently increases with time. I believe this means that on average during these hours, the bot simply doesn't have the throughput to keep up with demand.

**Third thing**: There's an obvious pattern where the latency drops down occasionally. I'm guessing the bot is hitting some sort of error and resetting. Unclear if the bot is dropping commands during these events.

_Edit_: Not all of these conclusions are accurate; see below for updated thoughts.

**Comment by TwiN** [comment]
@jimbobur might be losing his place as our professional graph maker now that @rickles42 made a graph of his own!

Jokes aside, I have also noticed something similar to your observations. I don't think that the bot hitting Reddit's API is the only reason why the bot is slow.

**Comment by rickles42** [comment]
Haha watch out @jimbobur my ugly Excel graphs are gonna steal your throne! /s

> I don't think that the bot hitting Reddit's API is the only reason why the bot is slow.

@TwinProduction It's possible you're right. We would need some detailed tracing to know for sure -- maybe print out precise timestamps at each stage of command processing so we can see where processing is getting blocked the longest. I still think we're just way maxing out the Reddit API limit, so PRAW calls that do API calls behind the scenes are blocking for significant times.

I'm only now internalizing the fact that Reddit's API limit (~60 calls/min) applies to both reads (e.g. get a batch of comments) and writes (e.g. post a comment). Before I was kind of just thinking of it as 60 posts/min. So it's possible that we're chewing through that API call limit with read requests---for example, when we check the comment's parent comment, does that result in another API call from PRAW?

**Comment by rickles42** [comment]
Okay I've thought about this data some more and examined the code, and I think I have a better understanding of what's going on.

It's a bit complicated to explain in text but **tl;dr** the bot is definitely not keeping pace with demand (at least during these hours) but it's not actually getting slower over time as I suggested above.

**Details**: The triangle shapes aren't really a case of the bot's latency increasing---actually the time to process each comment is staying pretty constant. Instead, each triangle reflects how the bot is working its way through a single batch of inbox comments returned by PRAW in the main loop. Basically, PRAW returns a batch of inbox comments all at once and waits for the bot to iterate through them all before PRAW grabs the next batch for the bot.

That next batch will once again be the newest comments in the inbox at that point in time. Since the bot is a bit slower than the incoming demand, this means that most of the time, all the newest comments were posted while the bot was processing the previous batch.

The big spikes represent times when the bot was actually able to make it through all the new comments of one batch and eat into the comments from the previous batch. But it's clear that during these hours, that's pretty rare, and the bot is generally falling further and further behind.

**Comment by jimbobur** [comment]
@TwinProduction @rickles42 I'm gonna step my game up and start drawing graphs by hand in the style of a Jackson Pollock painting  
  
![image](https://user-images.githubusercontent.com/34943023/41153106-b354861e-6b0d-11e8-917e-6b999b5bfa35.png)

**Comment by rickles42** [comment]
More data! Today I recorded every request made to the bot. Here's the breakdown:

![untitled](https://user-images.githubusercontent.com/81503/41186254-605636d4-6b48-11e8-8456-0cc8496f3f11.png)

(Valid requests made to the bot between 11AM-5PM PST today.)

**Conclusion**: We've been talking about getting rid of some of the commands and moving functionality to the website. Well, the only one it might make sense to remove is !balance, and even that one is iffy. Removing it could save us ~15% of our replies, but to avoid user confusion it would probably be best to leave the command in place and simply include an updated balance when we tell people how their investments did. That, plus having information on the website, would probably eliminate most of the !balance calls anyway, without forcing anyone's hand (always a good thing).

**Comment by rickles42** [comment]
I've made some more charts from today's activity (11AM-5PM PST today).

Below, each thin bar represents the number of valid user _requests_ posted during that sixty-second period. Over the whole six hours, there were 2867 requests, for an average of **8.0 requests per minute**:

![requests](https://user-images.githubusercontent.com/81503/41188743-2eff80d4-6b77-11e8-9230-2511ec2a4769.png)

The chart below shows the number of _responses_ posted by the bot per sixty-second period. Over the whole six hours, there are 2691 responses, for an average of **7.5 responses per minute**.

![responses](https://user-images.githubusercontent.com/81503/41188744-3e6e7200-6b77-11e8-8226-a272c8287f12.png)

If these measurements are accurate, then the bot was nearly keeping up with demand this afternoon, and I'm rather impressed! I'll try some further analysis to see how many requests went unanswered, to see if that supports the claim that we were only falling behind by 0.5 request per minute.

**Comment by rickles42** [comment]
During this six-hour period I recorded 182 unserviced requests (i.e. requests that didn't get a response). Here's roughly where they are:

![unserviced](https://user-images.githubusercontent.com/81503/41190106-94f478fc-6b8d-11e8-8a10-c8c2efad4fe2.png)

(Don't worry, the dark bits don't mean the bot was missing _all_ the requests. Just more than at other times.)

182 dropped requests over 6 hours is almost exactly 0.5/min, the average rate we predicted from the earlier charts.

**Comment by thecsw** [comment]
Oh boy, I love graphs. I will touch myself tonight~~, kidding. Very nice! We have the issue, however I think the issue will be resolved because of the reboot. Users would stop uncontrollably investing in memes. I wait for a decrease in number of requests per hour.

**Comment by rickles42** [comment]
Pull request #123 should also help with this by saving Reddit API calls

**Comment by thecsw** [comment]
Okay, I will close this then. We are actively working on this issue and multiple solutions have been implemented.

**Comment by rickles42** [comment]
I'll re-run some latency analysis once the bot is back under full load, and we'll see if we've improved throughput enough to keep up with demand.
