### ISSUE TITLE
Investors can make profit from posts with 0 upvotes

### ISSUE THREAD

**Issue by DaliTimelord** [thecsw/memeinvestor_bot#89]
This is not a _serious_ issue, but it does raise some concerns on how powerful a single vote can be and how it affects profits.

Given the current state of the algorithm, there is relatively no risk in investing something with 0 score, because it can't have a lower score than that. You only lose profits if a post doesn't gain score or only has a lower score after you've invested.

This means that memes that... attract downvotes are actually very profitable. One can invest in posts that have 0 upvotes, wait, then upvote before four hours. By then, the post has lost attention and is probably 50 pages away from new.

See [Example 1](https://www.reddit.com/r/MemeEconomy/comments/8pdut6/memes_that_are_too_versatile_are_overused_and_die/).

It's a bit counter-intuitive but hey that's economics for you.

**Comment by DaliTimelord** [comment]
Edit: Calculation part is in memeinvestor_bot/src/calculator.py:

```
...
# Calculate relative change
    if old != 0:
        rel_change = (new - old) / abs(old)
    # If starting upvotes was zero, avoid dividing by zero
    else:
        rel_change = new

mult = pow((rel_change+1), scale_factor)

 # Investment must grow by more than a threshold amount to win. Decide if
 # investment was successful and whether you get anything back at all.
 win_threshold = 1.2

    if mult > win_threshold:
        investment_success = True
        return_money = True
...
```

**Comment by jimbobur** [comment]
Hi, thanks for your input, we are aware of this issue and a solution has been in active development since Sunday. Please see comments on issues [#74](https://github.com/MemeInvestor/memeinvestor_bot/issues/74) and [#84](https://github.com/MemeInvestor/memeinvestor_bot/issues/84#issuecomment-395425035).
