### ISSUE TITLE
Suggestion: !active command to show users how many total active trades there are

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#9]
Could be fun for users to see how many investments are currently awaiting evaluation. This would kind of mimic the concept of "market volume" in the real stock markets. The command could give the total number of active trades, plus the total amount of MemeCoin currently on the line.

**Comment by thecsw** [comment]
I added two new options. 
!active will show the number of active investments on your account.
!market will show the whole market's status.

[Fix](https://github.com/thecsw/memeinvestor_bot/commit/ea96f57e7dd4e90d9dfee8abd83f358ac8397d3a)
