### ISSUE TITLE
Prevent investing in stickied posts?

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#90]
When a r/memeeconomy post is stickied, the submitter agent still makes an Invest Here! comment and people are able to invest in the stickied post. But since these posts are not usually memes, that means people are investing in something that's not a meme! Up to you guys, but maybe we should ignore stickied posts.

**Comment by robalb** [comment]
Stickied posts never get more than 100 or 200 upvotes, investing in this kind of posts won't be beneficial with the new formula

**Comment by rickles42** [comment]
You're probably right. But even so, do you think it's nicer if the bot is "pure" and only allows people to invest in memes, or is it fun/funny to have people be able to invest in stickies?

**Comment by thecsw** [comment]
Okay, I will work on this.
