### ISSUE TITLE
Add bot health monitoring service

### ISSUE THREAD

**Issue by rickles42** [thecsw/memeinvestor_bot#98]
We should have a service that can watch the bot's behavior and detect certain problematic patterns.

Possibilities include:
 - Detect when one of the service containers is crashing/restarting
 - Detect when the bot has stopped replying to requests
 - Detect if the bot's latency is getting high (large numbers of requests are aging past the 15 minute statute of limitations)

Maybe status could be displayed via another website off of memes.market. Or maybe we could message status to the bot runners directly.

**Comment by thecsw** [comment]
Maybe we can make a bot on telegram that will report all of this? If so, I can do it. But firstly, I need some tools, triggers that will notify if something happened.

**Comment by rickles42** [comment]
I'm positive we can find a way to integrate with Telegram or Slack.

**Comment by nickmahdavi** [comment]
I see that logging has been incorporated into the bot's functions... perhaps build this directly into the bot itself, have it report back in real-time?

**Comment by thecsw** [comment]
We have a running cAdvisor up and running that tells us everything we need. For logs, we can just see the containers' logs. Closing this issue.
